//! Game Builder: turn solo options into a player YAML for the Archipela-Go 2 apworld.

use crate::solo::SoloOptions;

pub const GAME_NAME: &str = "Archipela-Go 2: Electric Boogaloo";

fn list(v: &[String]) -> String {
    format!("[{}]", v.join(", "))
}

pub fn build_yaml(player_name: &str, o: &SoloOptions) -> String {
    let modes: Vec<String> = o.zone_modes.iter().map(|m| m.name().to_string()).collect();
    let b = |x: bool| if x { "true" } else { "false" };
    format!(
        "name: {name}\ngame: \"{game}\"\ndescription: Generated by the Archipela-Go 2 app\n\"{game}\":\n  goal: {goal}\n  goal_target: {gt}\n  number_of_trips: {n}\n  zone_modes: {zm}\n  easy_share: {e}\n  medium_share: {m}\n  hard_share: {h}\n  minutes_per_tier: {mpt}\n  minimum_distance: {md}\n  quest_types: {qt}\n  enabled_traps: {et}\n  trap_rate: {tr}\n  enable_effort_reductions: {er}\n  enable_scouting_distance_bonuses: {sc}\n  enable_collection_distance_bonuses: {co}\n  reduction_percent: {rp}\n  fog_of_war: {fog}\n  return_home: {rh}\n  death_link: false\n",
        name = player_name,
        game = GAME_NAME,
        goal = o.goal,
        gt = o.goal_target,
        n = o.number_of_trips,
        zm = list(&modes),
        e = o.easy_share,
        m = o.medium_share,
        h = o.hard_share,
        mpt = o.minutes_per_tier,
        md = o.min_distance_m,
        qt = list(&o.quest_types),
        et = list(&o.enabled_traps),
        tr = o.trap_rate,
        er = b(o.enable_effort_reductions),
        sc = b(o.enable_scouting),
        co = b(o.enable_collection),
        rp = o.reduction_percent,
        fog = b(o.fog_of_war),
        rh = b(o.return_home),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::Mode;

    #[test]
    fn yaml_has_every_option_key_the_apworld_example_uses() {
        let example = include_str!("../../apworld/docs/example.yaml");
        let ours = build_yaml("Tester", &SoloOptions::default());
        for line in example.lines() {
            let t = line.trim();
            if t.starts_with('#') || !t.contains(':') || t.starts_with("name") || t.starts_with("game") || t.starts_with("description") || t.starts_with('"') {
                continue;
            }
            let key = t.split(':').next().unwrap();
            assert!(ours.contains(&format!("  {key}:")), "our YAML is missing option `{key}` that the apworld example uses");
        }
    }

    #[test]
    fn modes_and_lists_are_rendered_for_the_apworld() {
        let o = SoloOptions { zone_modes: vec![Mode::Walk, Mode::Bike, Mode::Drive], goal: "treasure_hunt".into(), ..SoloOptions::default() };
        let y = build_yaml("Me", &o);
        assert!(y.contains("zone_modes: [walk, bike, drive]") && y.contains("goal: treasure_hunt") && y.contains("name: Me"));
        assert!(y.contains("enable_effort_reductions: false"));
    }
}
