//! Game Builder: turn solo options into a player YAML for the Archipela-Go 2 apworld.

use crate::goal::{goal_target_option, goal_yaml_name};
use crate::slot::GoalMode;
use crate::solo::SoloOptions;

/// The game name registered by the apworld.
pub const GAME_NAME: &str = "Archipela-Go 2: Electric Boogaloo";

fn list(v: &[String]) -> String {
    format!("[{}]", v.join(", "))
}

/// Archipelago player YAML for `player_name` built from the solo `o` options.
#[must_use]
pub fn build_yaml(player_name: &str, o: &SoloOptions) -> String {
    let modes: Vec<String> = o.zone_modes.iter().map(|m| m.name().to_string()).collect();
    let b = |x: bool| if x { "true" } else { "false" };
    let goals = o.goal_list();
    let selection: Vec<String> = goals.iter().map(|g| goal_yaml_name(&g.id).to_string()).collect();
    let requirement = match o.goal_mode {
        GoalMode::Any => "require_any_one_goal",
        GoalMode::All => "require_all_goals",
        GoalMode::AtLeast => "require_at_least_n_goals",
    };
    // Each counting goal has its own option; one not chosen keeps its default (the apworld ignores it).
    let target = |option: &str| -> u32 {
        ["zone_conqueror", "quest_dex", "marathon", "explorer", "streak", "boss_rush"]
            .into_iter()
            .filter_map(|id| goal_target_option(id).filter(|(name, _)| *name == option).map(|(_, default)| (id, default)))
            .map(|(id, default)| goals.iter().find(|g| g.id == id).map_or(default, |g| if g.target == 0 { default } else { g.target }))
            .next()
            .unwrap_or(0)
    };
    // The apworld has one list of quest types for the whole game: a game with per-zone lists exports their union.
    let mut quest_types: Vec<String> = Vec::new();
    for t in o.zone_quest_types.iter().flatten().chain(if o.zone_quest_types.iter().any(|z| !z.is_empty()) { [].iter() } else { o.quest_types.iter() }) {
        if !quest_types.contains(t) {
            quest_types.push(t.clone());
        }
    }
    format!(
        "name: {name}\ngame: \"{game}\"\ndescription: Generated by the Archipela-Go 2 app\n\"{game}\":\n  goal_selection: {gs}\n  goal_requirement: {req}\n  goals_required: {need}\n  goal_zone_conqueror_percent: {zc}\n  goal_quest_dex_kinds: {qd}\n  goal_marathon_kilometers: {mk}\n  goal_explorer_cells: {ec}\n  goal_streak_days: {sd}\n  goal_boss_rush_hard_quests: {br}\n  number_of_trips: {n}\n  zone_modes: {zm}\n  easy_share: {e}\n  medium_share: {m}\n  hard_share: {h}\n  minutes_per_tier: {mpt}\n  minimum_distance: {md}\n  quest_types: {qt}\n  enabled_traps: {et}\n  trap_rate: {tr}\n  enable_effort_reductions: {er}\n  enable_scouting_distance_bonuses: {sc}\n  enable_collection_distance_bonuses: {co}\n  reduction_percent: {rp}\n  fog_of_war: {fog}\n  return_home: {rh}\n  death_link: false\n",
        name = player_name,
        game = GAME_NAME,
        gs = list(&selection),
        req = requirement,
        need = o.goal_need.clamp(1, 12),
        zc = target("goal_zone_conqueror_percent"),
        qd = target("goal_quest_dex_kinds"),
        mk = target("goal_marathon_kilometers"),
        ec = target("goal_explorer_cells"),
        sd = target("goal_streak_days"),
        br = target("goal_boss_rush_hard_quests"),
        n = o.number_of_trips,
        zm = list(&modes),
        e = o.easy_share,
        m = o.medium_share,
        h = o.hard_share,
        mpt = o.minutes_per_tier,
        md = o.min_distance_m,
        qt = list(&quest_types),
        et = list(&o.enabled_traps),
        tr = o.trap_rate,
        er = b(o.enable_effort_reductions),
        sc = b(o.enable_scouting),
        co = b(o.enable_collection),
        rp = o.reduction_percent,
        fog = b(o.fog_of_war),
        rh = b(o.return_home),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::Mode;
    use crate::slot::{GoalMode, GoalSpec};

    #[test]
    fn yaml_has_every_option_key_the_apworld_example_uses() {
        let example = include_str!("../../apworld/docs/example.yaml");
        let ours = build_yaml("Tester", &SoloOptions::default());
        for line in example.lines() {
            let t = line.trim();
            if t.starts_with('#') || !t.contains(':') || t.starts_with("name") || t.starts_with("game") || t.starts_with("description") || t.starts_with('"') {
                continue;
            }
            let key = t.split(':').next().unwrap();
            assert!(ours.contains(&format!("  {key}:")), "our YAML is missing option `{key}` that the apworld example uses");
        }
    }

    #[test]
    fn modes_and_lists_are_rendered_for_the_apworld() {
        let o = SoloOptions { zone_modes: vec![Mode::Walk, Mode::Bike, Mode::Drive], goal: "treasure_hunt".into(), ..SoloOptions::default() };
        let y = build_yaml("Me", &o);
        assert!(y.contains("zone_modes: [walk, bike, drive]") && y.contains("goal_selection: [Treasure Hunt]") && y.contains("name: Me"));
        assert!(y.contains("enable_effort_reductions: false"));
    }

    #[test]
    fn several_goals_use_the_apworlds_names_requirement_and_targets() {
        let g = |id: &str, target: u32| GoalSpec { id: id.into(), target };
        let o = SoloOptions {
            goals: vec![g("boss", 0), g("quest_dex", 9), g("marathon", 0)],
            goal_mode: GoalMode::AtLeast,
            goal_need: 2,
            ..SoloOptions::default()
        };
        let y = build_yaml("Me", &o);
        assert!(y.contains("goal_selection: [The Big One, Quest-dex, Marathon]"), "{y}");
        assert!(y.contains("goal_requirement: require_at_least_n_goals") && y.contains("goals_required: 2"));
        assert!(y.contains("goal_quest_dex_kinds: 9"), "a chosen target is written");
        assert!(y.contains("goal_marathon_kilometers: 42"), "an unset target uses the goal's default");
        let any = build_yaml("Me", &SoloOptions { goals: vec![g("boss", 0)], goal_mode: GoalMode::Any, ..SoloOptions::default() });
        assert!(any.contains("goal_requirement: require_any_one_goal"));
        let all = build_yaml("Me", &SoloOptions { goals: vec![g("boss", 0)], goal_mode: GoalMode::All, ..SoloOptions::default() });
        assert!(all.contains("goal_requirement: require_all_goals"));
    }

    #[test]
    fn per_zone_quest_types_are_exported_as_one_union() {
        let o = SoloOptions {
            quest_types: vec!["reach".into()],
            zone_quest_types: vec![vec!["park".into()], vec!["dwell".into(), "park".into()]],
            ..SoloOptions::default()
        };
        let y = build_yaml("Me", &o);
        assert!(y.contains("quest_types: [park, dwell]"), "{y}");
    }
}
