package dev.apgo2

import android.Manifest
import android.annotation.SuppressLint
import android.content.Context
import android.location.Location
import android.location.LocationListener
import android.location.LocationManager
import android.os.Build
import android.os.Bundle
import android.os.SystemClock
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import org.maplibre.android.geometry.LatLng
import uniffi.apgo_ffi.ApEvent
import uniffi.apgo_ffi.ApSession
import uniffi.apgo_ffi.FillMode
import uniffi.apgo_ffi.GeoPoint
import uniffi.apgo_ffi.ReceivedItemOut
import uniffi.apgo_ffi.TripSpecIn
import uniffi.apgo_ffi.coreVersion
import uniffi.apgo_ffi.generateTripsFor
import kotlin.math.pow

private const val CHECK_RADIUS_M = 40f

/** What the apworld assigned to a location (slot_data.trips). */
private data class SlotTrip(val locationId: Long, val tier: Int, val keyNeeded: Int)

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { MaterialTheme { Surface(Modifier.fillMaxSize()) { Game() } } }
    }

    @SuppressLint("MissingPermission")
    private fun bestProvider(lm: LocationManager): String? {
        val providers = buildList {
            if (Build.VERSION.SDK_INT >= 31) add(LocationManager.FUSED_PROVIDER)
            add(LocationManager.GPS_PROVIDER)
            add(LocationManager.NETWORK_PROVIDER)
        }
        return providers.firstOrNull { lm.isProviderEnabled(it) }
    }

    @Composable
    fun Game() {
        val scope = rememberCoroutineScope()
        var realLoc by remember { mutableStateOf<Location?>(null) }
        var simLoc by remember { mutableStateOf<LatLng?>(null) }
        var permission by remember { mutableStateOf(false) }
        var status by remember { mutableStateOf("Grant location, connect, then fill.") }

        var url by remember { mutableStateOf("localhost:38281") }
        var slot by remember { mutableStateOf("Tester") }
        var session by remember { mutableStateOf<ApSession?>(null) }
        var apStatus by remember { mutableStateOf("not connected") }
        var slotTrips by remember { mutableStateOf<List<SlotTrip>>(emptyList()) }
        var tierStep by remember { mutableStateOf(0.0) }
        var reductionPct by remember { mutableStateOf(8) }
        var items by remember { mutableStateOf<List<ReceivedItemOut>>(emptyList()) }
        val done = remember { mutableStateListOf<Long>() }
        var generated by remember { mutableStateOf<List<GameTrip>>(emptyList()) }
        val log = remember { mutableStateListOf<String>() }

        val keys = items.count { it.name == "Progressive Key" }
        val reductions = items.count { it.name == "Progressive Distance Reduction" }
        val me: LatLng? = simLoc ?: realLoc?.let { LatLng(it.latitude, it.longitude) }

        val shown = generated.map {
            it.copy(state = if (it.locationId in done) "done" else if (it.keyNeeded > keys) "locked" else "open")
        }

        val askLocation = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { permission = it }

        // Live location while the screen is up.
        DisposableEffect(permission) {
            if (!permission) return@DisposableEffect onDispose {}
            val lm = getSystemService(Context.LOCATION_SERVICE) as LocationManager
            val provider = bestProvider(lm)
            val listener = LocationListener { loc -> realLoc = loc }
            if (provider != null) {
                @SuppressLint("MissingPermission")
                lm.requestLocationUpdates(provider, 1000L, 0f, listener)
                @SuppressLint("MissingPermission")
                lm.getLastKnownLocation(provider)?.let { realLoc = it }
            }
            onDispose { lm.removeUpdates(listener) }
        }

        // Poll the Archipelago connection.
        LaunchedEffect(session) {
            val s = session ?: return@LaunchedEffect
            while (true) {
                val events = withContext(Dispatchers.IO) {
                    runCatching { s.poll() }.getOrElse { listOf(ApEvent.Error("poll failed: ${it.message}")) }
                }
                events.forEach { e ->
                    when (e) {
                        is ApEvent.Print -> log.add(e.text)
                        is ApEvent.Error -> log.add("ERROR: ${e.detail}")
                        is ApEvent.Connected -> {
                            val data = s.slotDataJson()?.let { JSONObject(it) }
                            val arr = data?.optJSONArray("trips")
                            slotTrips = (0 until (arr?.length() ?: 0)).map {
                                val o = arr!!.getJSONObject(it)
                                SlotTrip(o.getLong("location_id"), o.getInt("distance_tier"), o.getInt("key_needed"))
                            }
                            tierStep = data?.optDouble("tier_step_m", 0.0) ?: 0.0
                            reductionPct = data?.optInt("reduction_percent", 8) ?: 8
                            status = "Connected: ${slotTrips.size} trips from the apworld."
                        }
                        else -> {}
                    }
                }
                apStatus = s.status()
                items = withContext(Dispatchers.IO) { runCatching { s.receivedItems() }.getOrDefault(emptyList()) }
                delay(250)
            }
        }

        // Geofence: reaching an open, unchecked trip sends its check.
        LaunchedEffect(me, shown) {
            val pos = me ?: return@LaunchedEffect
            val s = session ?: return@LaunchedEffect
            shown.filter { it.state == "open" }.forEach { t ->
                val d = FloatArray(1)
                Location.distanceBetween(pos.latitude, pos.longitude, t.lat, t.lon, d)
                if (d[0] <= CHECK_RADIUS_M) {
                    runCatching { s.sendCheck(t.locationId) }
                        .onSuccess { done.add(t.locationId); log.add("Reached ${t.name} (tier ${t.tier}), check sent") }
                        .onFailure { log.add("check failed: ${it.message}") }
                }
            }
        }

        fun fill(mode: FillMode) {
            val c = me ?: return run { status = "No location yet" }
            if (slotTrips.isEmpty()) return run { status = "Connect first (need slot_data)" }
            status = "Filling zone (${mode.name.lowercase()})..."
            scope.launch {
                val t0 = SystemClock.elapsedRealtime()
                val step = tierStep * (1 - reductionPct / 100.0).pow(reductions)
                val result = withContext(Dispatchers.IO) {
                    runCatching {
                        generateTripsFor(
                            GeoPoint(c.latitude, c.longitude), step,
                            slotTrips.map { TripSpecIn(it.locationId, it.tier.toUByte()) },
                            1uL, mode, cacheDir.absolutePath,
                        )
                    }
                }
                val ms = SystemClock.elapsedRealtime() - t0
                result.onSuccess { out ->
                    val keyOf = slotTrips.associate { it.locationId to it.keyNeeded }
                    generated = out.map {
                        GameTrip(it.locationId, it.tier.toInt(), keyOf[it.locationId] ?: 0, it.name, it.lat, it.lon, it.distanceM, "open")
                    }
                    status = "${out.size} trips placed in $ms ms (${out.count { it.inBand }} in band)"
                }.onFailure { status = "Fill failed: ${it.message}" }
            }
        }

        Column(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal = 8.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
            Text("Archipela-Go 2  ·  ${coreVersion()}", style = MaterialTheme.typography.titleSmall)
            Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                OutlinedTextField(url, { url = it }, label = { Text("Server") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(slot, { slot = it }, label = { Text("Slot") }, singleLine = true, modifier = Modifier.weight(1f))
            }
            Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                Button(onClick = { askLocation.launch(Manifest.permission.ACCESS_FINE_LOCATION) }) { Text("Location", fontSize = 12.sp) }
                Button(onClick = {
                    log.clear(); done.clear(); generated = emptyList(); items = emptyList()
                    session = ApSession.connect(url, slot, null, cacheDir.resolve("ap").absolutePath)
                }) { Text("Connect", fontSize = 12.sp) }
                Button(onClick = { fill(FillMode.CELLS) }) { Text("Fill: cells", fontSize = 12.sp) }
                Button(onClick = { fill(FillMode.STREETS) }) { Text("Fill: streets", fontSize = 12.sp) }
            }
            Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                Button(onClick = {
                    val next = shown.firstOrNull { it.state == "open" }
                    if (next != null) simLoc = LatLng(next.lat, next.lon) else status = "No open trips to teleport to"
                }) { Text("DEV: teleport to next", fontSize = 12.sp) }
                Button(onClick = { simLoc = null }) { Text("Use real GPS", fontSize = 12.sp) }
            }
            Text(
                "AP: $apStatus | keys $keys | reductions $reductions | done ${done.size}/${generated.size} | " +
                    "${shown.count { it.state == "locked" }} locked | ${if (simLoc != null) "SIMULATED" else "real"} GPS",
                fontSize = 12.sp,
            )
            Text(status, fontSize = 12.sp)
            Text(log.takeLast(3).joinToString("\n"), fontSize = 11.sp)
            TripMap(shown, me, Modifier.weight(1f).fillMaxSize())
        }
    }
}
