#!/usr/bin/env python3
"""Generate docs/context/quest-catalog.md from core/data/quest_catalog.json (the source of truth)."""

import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
cat = json.loads((root / "core/data/quest_catalog.json").read_text(encoding="utf-8"))


def filt(kind: dict) -> str:
    if not kind["any_of"]:
        return "(no map data needed)"
    groups = []
    for group in kind["any_of"]:
        groups.append(" + ".join(f"{c['key']}={'/'.join(c['values'])}" for c in group))
    out = " OR ".join(groups)
    if kind.get("none_of"):
        out += (
            " (not "
            + ", ".join(f"{c['key']}={'/'.join(c['values'])}" for c in kind["none_of"])
            + ")"
        )
    return out.replace("|", "\\|").replace("*", "\\*")


def verify(kind: dict) -> str:
    v = dict(kind["verify"])
    t = v.pop("type")
    extra = ", ".join(f"{k}={val}" for k, val in v.items())
    return f"{t}" + (f" ({extra})" if extra else "")


lines = [
    "# Context Doc: Quest Catalog (generated)",
    "",
    "_Generated by `scripts/catalog_doc.py` from `core/data/quest_catalog.json`. Edit the JSON, then rerun. Do not edit this file by hand._",
    "",
    f"{len(cat['kinds'])} quest kinds in {len(cat['families'])} families. A **family** is what the apworld assigns to a slot; the phone picks a **kind** and a place from the realm's atlas.",
    "A kind appears for a realm only if the scan found at least `min_features` matching places and the realm's mode is allowed.",
    "",
]
for fam in cat["families"]:
    ks = [k for k in cat["kinds"] if k["family"] == fam]
    lines += [
        f"## {fam} ({len(ks)})",
        "",
        "| Quest | What | Map data (OSM) | Proof | Modes |",
        "| -- | -- | -- | -- | -- |",
    ]
    for k in ks:
        flag = " (named)" if k.get("require_name") else ""
        lines.append(
            f"| **{k['name']}** | {k['blurb']} | {filt(k)}{flag} | {verify(k)} | {', '.join(k['modes'])} |"
        )
    lines.append("")
(root / "docs/context/quest-catalog.md").write_text("\n".join(lines), encoding="utf-8")
print(f"wrote docs/context/quest-catalog.md ({len(cat['kinds'])} kinds)")
sys.exit(0)
