plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt)
    alias(libs.plugins.kover)
}

android {
    namespace = "dev.apgo2"
    compileSdk = 37

    defaultConfig {
        applicationId = "dev.apgo2.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.0.1"
        ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
    }

    buildFeatures { compose = true }

    lint {
        warningsAsErrors = true
        abortOnError = true
        checkDependencies = true
        checkReleaseBuilds = true
    }
}

kotlin { compilerOptions { allWarningsAsErrors.set(true) } }

spotless {
    kotlin {
        target("src/**/*.kt")
        targetExclude("src/main/kotlin/uniffi/**") // generated by uniffi-bindgen
        ktlint(libs.versions.ktlint.get())
            .customRuleSets(listOf("io.nlopez.compose.rules:ktlint:${libs.versions.composeRulesKtlint.get()}"))
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint(libs.versions.ktlint.get())
    }
}

detekt {
    buildUponDefaultConfig = true
    allRules = true
    config.setFrom(rootProject.file("config/detekt.yml"))
    source.setFrom("src/main/java", "src/main/kotlin", "src/test/java")
}

tasks.withType<dev.detekt.gradle.Detekt>().configureEach {
    exclude("**/uniffi/**") // generated by uniffi-bindgen
}

// HelpTextTest checks the help copy against the apworld's goal and family names (the monorepo is checked out whole, also in CI).
tasks.withType<Test>().configureEach {
    systemProperty("apworld.constants", rootProject.file("../apworld/ap_go2/constants.py").absolutePath)
}

dependencies {
    detektPlugins(libs.compose.rules.detekt)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.tooling.preview)
    debugImplementation(libs.compose.tooling)
    implementation(libs.core.ktx)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.runtime.compose)
    implementation("${libs.jna.get()}@aar")
    implementation(libs.maplibre)
    implementation(libs.lucide)
    testImplementation(libs.junit)
    testImplementation(libs.org.json) // android.jar stubs org.json out in local unit tests
}

kover {
    reports {
        filters { excludes { packages("uniffi.*") } } // generated bindings
        verify { rule { minBound(15) } }
    }
}
